all:
	gcc -o ./mknod_test ./mknod_test.c -lpthread 
	gcc -o ./stat_test ./stat_test.c
	gcc -o ./smallfile_test ./smallfile_test.c -lpthread 
	gcc -g -o ./crash_test ./crash_test.c

clean:
	rm mknod_test
